
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'EQUALS LPAREN NAME NUMBER PLUS RPARENexpression : expression PLUS NAMEexpression : LPAREN expression RPARENexpression : NAME EQUALS expressionexpression : NUMBERexpression : NAME'
    
_lr_action_items = {'LPAREN':([0,3,6,],[3,3,3,]),'NAME':([0,3,5,6,],[2,2,8,2,]),'NUMBER':([0,3,6,],[4,4,4,]),'$end':([1,2,4,8,9,10,],[0,-5,-4,-1,-3,-2,]),'PLUS':([1,2,4,7,8,9,10,],[5,-5,-4,5,-1,5,-2,]),'EQUALS':([2,],[6,]),'RPAREN':([2,4,7,8,9,10,],[-5,-4,10,-1,-3,-2,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,3,6,],[1,7,9,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> expression PLUS NAME','expression',3,'p_expression_plus','parser.py',13),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_expression_paren','parser.py',20),
  ('expression -> NAME EQUALS expression','expression',3,'p_expression_equals','parser.py',24),
  ('expression -> NUMBER','expression',1,'p_expression_number','parser.py',29),
  ('expression -> NAME','expression',1,'p_expression_name','parser.py',33),
]
